version: "3"

services:
  sonarqube:
    image: sonarqube:8.3.1-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    volumes:
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "testebanco"
      MYSQL_DATABASE: "folhaPonto"
    expose:
      - 3306
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mysql-compose-network

networks:
  sonarnet:
  mysql-compose-network:

volumes:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  my-db: