server:
  port: ${PORT:8081}
spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
#  datasource:
#    password: testebanco
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/folhaPonto
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
  liquibase:
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  application:
    name: spring-cloud-eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: https://folha-ponto-eureka.herokuapp.com/eureka/
  instance:
    preferIpAddress: true
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
    hostname: folha-ponto-eureka.herokuapp.com
    non-secure-port: 80
    secure-port: 443