server:
  port: 8080

spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
  liquibase:
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
