spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    password: testebanco
#    url: jdbc:h2:mem:folhaPonto
#    username: sa
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.MySQL5Dialect

